bo/routes/backend.php
<?php

/*
|--------------------------------------------------------------------------
| Private
|--------------------------------------------------------------------------
*/

Route::group([
    'namespace'     => 'Backend',
    'prefix'        => 'backend',
    'middleware'    => [ 'web' ],
], function() {
    // backend login endpoints
    Route::get('login', 'Auth\LoginController@showLoginForm');
    Route::post('login', 'Auth\LoginController@login')->name('backend.login');
    Route::post('logout', 'Auth\LoginController@logout')->name('backend.logout');
});

Route::group([
    'namespace'     => 'Backend',
    'prefix'        => 'backend',
    'middleware'    => [ 'web', 'auth:admin' ],
], function() {
    // name prefix
    $name_prefix = [ 'as' => 'admin' ];

    //
    Route::get('/',                     'DashboardController@index')->name('backend');
    Route::get('/dashboard',            'DashboardController@dashboard')->name('admin.dashboard');
    Route::get('/dashboard/verticals',  'DashboardController@verticals')->name('admin.dashboard.verticals');

    // users
    Route::resource('admins',   'AdminsController', $name_prefix)->name('index', 'admin.admins')->parameters([ 'admins' => 'samsung' ]);
    Route::resource('users',    'UsersController', $name_prefix)->name('index', 'admin.users');
    Route::get('solicitudes',    'UsersController@solicitudes')->name('admin.solicitudes');
    Route::post('solicitudes/{id}',    'UsersController@solicitud')->name('admin.solicitud');
    Route::get('rechazados',    'UsersController@rechazados')->name('admin.rechazados');
    
    //
    Route::resource('divisions',        'DivisionsController', $name_prefix)->name('index', 'admin.divisions');
    Route::resource('subcategorias',        'SubCategoriaController', $name_prefix)->name('index', 'admin.subcategorias');
    Route::resource('images',           'ImagesController', $name_prefix)->name('index', 'admin.images')->parameters([ 'files' => 'image' ]);
    Route::resource('products',         'ProductsController', $name_prefix)->name('index', 'admin.products');
    Route::post('stock/{id}', 'ProductsController@stock')->name('admin.stock');
    Route::resource('companies',        'CompaniesController', $name_prefix)->name('index', 'admin.companies');
    Route::resource('verticals',        'VerticalsController', $name_prefix)->name('index', 'admin.verticals');
    Route::resource('opportunities',    'OpportunitiesController', $name_prefix)->name('index', 'admin.opportunities');
    Route::resource('offers',           'OffersController', $name_prefix)->name('index', 'admin.offers');

    // private storage
    Route::get('storage/{file}',        'StorageController@get')->name('storage.get');
    //acciones que otorgan puntos
    Route::get('acciones', 'AccionController@index')->name('admin.acciones');
    Route::post('acciones/update/{id}', 'AccionController@update')->name('admin.acciones.update');

    Route::get('proteccion', 'ProtectController@oportunidades_pendientes')->name('admin.proteccion');
    Route::get('leads', 'OpportunitiesController@leads')->name('admin.leads');
    Route::get('leads/{id}', 'OpportunitiesController@lead')->name('admin.lead');
    Route::post('lead/{id}', 'OpportunitiesController@otorgar_lead')->name('admin.otorgar_lead');
    Route::get('oportunidad/{id}', 'ProtectController@oportunidad')->name('admin.proteccionShow');
    Route::post('proteccion/oportunidad', 'ProtectController@proteccion')->name('admin.proteccion_state');
    Route::get('opp_protegidas', 'ProtectController@opp_protegidas')->name('admin.opp_protegidas');
    Route::get('opp_rechazadas', 'ProtectController@opp_rechazadas')->name('admin.opp_rechazadas');

    //ranks
    Route::get('rank_puntos', 'RankingController@rank_puntos')->name('admin.rank_puntos');
    Route::get('rank_puntos/periodo', 'RankingController@rank_puntos_periodo')->name('admin.rank_puntos_periodo');

    Route::get('rank_oportunidades', 'RankingController@rank_opp')->name('admin.rank_oportunidades');
    Route::get('rank_oportunidades/periodo', 'RankingController@rank_oportunidades_periodo')->name('admin.rank_oportunidades_periodo');
    
    Route::get('rank_monto', 'RankingController@rank_monto')->name('admin.rank_monto');
    Route::get('rank_monto/periodo', 'RankingController@rank_monto_periodo')->name('admin.rank_monto_periodo');

    Route::post('oportunidad/precio/{id}', 'OpportunitiesController@precio_asignado')->name('admin.oportunidad_precio');
  
    Route::post('/addProductOpp',  'OpportunitiesController@addProductOpp');
    Route::post('/deleteOppProduct', 'OpportunitiesController@deleteOppProduct');
    Route::delete('/opportunities/{id}', 'OpportunitiesController@destroy')->name('opportunities.destroy');

});

bo/routes/frontend.php
<?php

/*
|--------------------------------------------------------------------------
| Public with authentication needed
|--------------------------------------------------------------------------
*/
Route::group([
    'namespace'     => 'Frontend',
], function() {
    Route::get('/register_client', 'UserController@create');
    Route::post('/register_client', 'UserController@store')->name('register_client');
});
Route::group([
    'namespace'     => 'Frontend',
    'middleware'    => [ 'auth' ],
], function() {
    // dashboard
    Route::get('/dashboard',            'DashboardController@index')->name('dashboard');

    Route::resource('opportunities',            'OpportunitiesController', [
        'only'  => [ 'show', 'create', 'edit', 'update', 'store' ],
        'names' => [ 'index' => 'opportunities.show' ]
    ]);
    Route::resource('opportunities.offers',     'OffersController', [
        'only'  => [ 'show', 'create', 'store', 'update', 'edit', 'destroy' ],
        'names' => [ 'index' => 'opportunities.offers' ]
    ]);
    Route::put('opportunities/{opportunity}/offers/{offer}/accept', 'OffersController@accept')->name('opportunities.offers.accept');
    Route::put('opportunities/{opportunity}/offers/{offer}/reject', 'OffersController@reject')->name('opportunities.offers.reject');
    Route::resource('products',                 'PricesController', [
        'only'  => [ 'index', 'update' ],
        'names' => [ 'index' => 'products' ]
    ]);

    //json
    Route::get('/listProducts',            'OpportunitiesController@listProducts');
    Route::get('/listOppProducts',            'OpportunitiesController@listOppProducts');
    Route::post('/addProductOpp',  'OpportunitiesController@addProductOpp');
    Route::post('/deleteOppProduct', 'OpportunitiesController@deleteOppProduct');

    // private storage
    Route::get('storage/{file}',        'StorageController@get')->name('frontstorage.get');
    Route::post('opportunities/precio_solicitado/{id}', 'OpportunitiesController@precio_solicitado');
    Route::post('opportunities/aprobado/{id}', 'OpportunitiesController@aprobado');
    Route::post('opportunities/cerrar/{id}', 'OpportunitiesController@cerrar');
    Route::post('opportunities/perder/{id}', 'OpportunitiesController@perder');
    Route::post('opportunities/estado', 'DashboardController@actualizar');
    Route::post('opportunities/mail', 'OpportunitiesController@mail');
    Route::post('opportunities/obtener/{id}', 'OpportunitiesController@obtener');
});

bo/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Public
|--------------------------------------------------------------------------
*/
Route::group([
    'namespace'     => 'Frontend'
], function() {
    //
 //   Route::get('/',         'SiteController@index');
    Route::get('/',         function(){
        return redirect('/login');
    });
    Route::get('/home',     'SiteController@index');
    // Route::get('/contact',  'SiteController@contact');
    // web login endpoints
    Auth::routes();
});

bo/app/Http/Controllers/Backend/AccionController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\Accion;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class AccionController extends BackendController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $acciones = Accion::all();
        return view('puntajes.acciones.index', compact('acciones'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Accion  $accion
     * @return \Illuminate\Http\Response
     */
    public function show(Accion $accion)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Accion  $accion
     * @return \Illuminate\Http\Response
     */
    public function edit(Accion $accion)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Accion  $accion
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        
        $accion = Accion::find($id);
        $accion->puntos = $request->puntos;
        $accion->save();
        return redirect('/backend/acciones');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Accion  $accion
     * @return \Illuminate\Http\Response
     */
    public function destroy(Accion $accion)
    {
        //
    }
}

bo/app/Http/Controllers/Backend/AdminsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Backend\BackendController;
use App\Models\Samsung;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AdminsController extends BackendController {
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        // fetch all objects
        $users = Samsung::all();
        // show a list of objects
        return view('admins.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        // show create form
        return view('admins.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        // create resource
        $admin = new Samsung;
        // fill resource with request data
        $admin->fill($request->only( Samsung::createRules(true) ));
        // crypt password before saving
        $admin->password = bcrypt($admin->password);
        // set user type fixed to samsung (admins)
        $admin->type = 'samsung';
        // save resource
        if (!$admin->save())
            // redirect with errors
            return redirect()
                ->back()
                ->withErrors($admin->errors())
                ->withInput();
        // redirect to list
        return redirect()->route('admin.admins');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Samsung  $samsung
     * @return \Illuminate\Http\Response
     */
    public function show(Samsung $samsung) {
        // redirect to list
        return redirect()->route('admin.admins');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Samsung  $samsung
     * @return \Illuminate\Http\Response
     */
    public function edit(Samsung $samsung) {
        // show edit form
        return view('admins.edit', [ 'user' => $samsung ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Samsung  $samsung
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Samsung $samsung) {
        // check for password change
        if ($request->has('password') && $request->password !== null)
            // validate password change (password confirmation)
            $this->validate($request, Samsung::$passwordRules);
        else
            // remove password attribute from request to prevent null assignment
            $request->request->remove('password');
        // update resource with request data
        $samsung->fill($request->only( Samsung::updateRules($samsung->id, true) ));
        // check for password change
        if ($request->has('password'))
            // crypt password
            $samsung->password = bcrypt($samsung->password);
        // check if company was selected
        if ($samsung->company !== null)
            // update type based on Company
            $samsung->type = $samsung->company->type;
        // save resource
        if (!$samsung->save())
            // redirect with errors
            return redirect()
                ->back()
                ->withErrors($samsung->errors())
                ->withInput();
        // redirect to list
        return redirect()->route('admin.admins');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Samsung  $samsung
     * @return \Illuminate\Http\Response
     */
    public function destroy(Samsung $samsung) {
        // check current user or root account
        if (Auth::user()->id == $samsung->id || $samsung->id == 1) return back();
        // delete object
        $samsung->delete();
        // redirect to list
        return redirect()->route('admin.admins');
    }
}

bo/app/Http/Controllers/Backend/BackendController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

abstract class BackendController extends Controller {
    public function __construct() {
        // rewrite base path for views
        view()->addLocation(resource_path('views/backend/'));
    }
}

bo/app/Http/Controllers/Backend/DivisionsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Backend\BackendController;
use App\Models\Division;
use App\Models\SubCategoria;
use App\Models\File;
use Illuminate\Http\Request;

class DivisionsController extends BackendController {
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        // fetch all objects
        $divisions = Division::all();
        // show a list of objects
        return view('divisions.index', compact('divisions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        // load images
        $images = File::images()->get();
        // show create form
        return view('divisions.create', compact('images'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        // create resource
        $division = new Division;
        // fill resource with request data
        $division->fill($request->only( Division::createRules(true) ));
        // save resource
        if (!$division->save())
            // redirect with errors
            return redirect()
                ->back()
                ->withErrors($division->errors())
                ->withInput();
        // redirect to list
        return redirect()->route('admin.divisions');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Division  $division
     * @return \Illuminate\Http\Response
     */
    public function show(Division $division) {
        // redirect to list
        $subs = SubCategoria::where('division_id', $division->id)->get();
        return view('subcategorias.index', compact('subs'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Division  $division
     * @return \Illuminate\Http\Response
     */
    public function edit(Division $division) {
        // show edit form
        return view('divisions.edit', compact('division'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Division  $division
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Division $division) {
        // update object
        if (!$division->update($request->only( Division::updateRules($division->id, true) )))
            // redirect with errors
            return redirect()
                ->back()
                ->withErrors($division->errors())
                ->withInput();
        // redirect to list
        return redirect()->route('admin.divisions');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Division  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $division = Division::find($id);
        
        $division->delete();
        return redirect('/backend/divisions');
    }
}

bo/resources/views/backend/images/create.blade.php
@extends('layouts.master')

@section('page-name', 'Crear nueva Imágen')

@section('content')

<div class="card mb-3">
    <div class="card-header">
        <div class="row">
            <div class="col-6">
                <i class="fas fa-user-plus"></i>
                Añadir Imágen
            </div>
            <div class="col-6 d-flex justify-content-end">
                {{-- <a href="{{ route('admin.images.create') }}" class="btn btn-sm btn-primary">Añadir</a> --}}
            </div>
        </div>
    </div>
    <div class="card-body">
        <form method="POST" action="{{ route('admin.images.store') }}" enctype="multipart/form-data">
            @csrf
            @include('images.form')
        </form>
    </div>
</div>

@endsection

bo/resources/views/backend/images/form.blade.php
<div class="form-group">
    <label class="col-3 control-label">Imágen</label>
    <div class="col-6">
        <input name="file" type="file" class="form-control {{ $errors->has('name') ? 'is-danger' : '' }}" required placeholder="Imágen" value="{{ isset($image) && !old('file') ? $image->file : old('file') }}" accept="image/*">
    </div>
</div>

@if ($errors->any())
<div class="row">
    <div class="col-lg-6 mb-4">
        <div class="card bg-danger text-white shadow">
            <div class="card-body">
                Error
                @foreach ($errors->all() as $error)
                    <div class="text-white-50 small">{{ $error }}</div>
                @endforeach
            </div>
        </div>
    </div>
</div>
@endif

<div class="row">
    <div class="col-sm-3"></div>
    <div class="col-sm-9">
        <button type="submit" class="btn btn-success">Guardar</button>
        <a href="{{ route('admin.images') }}" class="btn btn-danger">Cancelar</a>
    </div>
</div>

bo/resources/views/backend/images/index.blade.php
@extends('layouts.master')

@section('page-name', 'Imágenes')

@section('content')

<div class="card mb-3">
    <div class="card-header">
        <div class="row">
            <div class="col-6">
                <i class="fas fa-table"></i>
                Lista de Imágenes
            </div>
            <div class="col-6 d-flex justify-content-end">
                <a href="{{ route('admin.images.create') }}" class="btn btn-sm btn-primary">Añadir</a>
            </div>
        </div>
    </div>
    <div class="card-body">
        @if ($images->count())
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th class="w-100px">ID</th>
                            <th>Nombre</th>
                            <th>Tipo</th>
                            <th>Imágen</th>
                            <th class="w-200px">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($images as $image)
                        <tr>
                            <td>{{ $image->getKey() }}</td>
                            <td>{{ $image->name }}</td>
                            <td>{{ $image->type }}</td>
                            <td><img src="{{ route('storage.get', [ 'file' => $image->getKey() ]) }}" class="mh-100px"></td>
                            <td class="text-center d-flex justify-content-around">
                                @include('components.actions', [
                                    'resource'  => 'images',
                                    'title'     => $image->name,
                                    'record'    => $image->getKey(),
                                    'actions'   => [ 'delete' ]
                                ])
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        @else
            <div class="text-center m-t-30 m-b-30 p-b-10">
                <h2><i class="fas fa-table text-custom"></i></h2>
                <h3>No se encontraron resultados</h3>
                <p class="text-muted">
                    Puedes agregar items haciendo click en el botón
                    <a href="{{ route('admin.images.create') }}" class="text-custom">
                        <ins>Añadir</ins>
                    </a>
                </p>
            </div>
        @endif
    </div>
</div>

@endsection