bo/routes/backend.php
<?php

/*
|--------------------------------------------------------------------------
| Private
|--------------------------------------------------------------------------
*/

Route::group([
    'namespace'     => 'Backend',
    'prefix'        => 'backend',
    'middleware'    => [ 'web' ],
], function() {
    // backend login endpoints
    Route::get('login', 'Auth\LoginController@showLoginForm');
    Route::post('login', 'Auth\LoginController@login')->name('backend.login');
    Route::post('logout', 'Auth\LoginController@logout')->name('backend.logout');
});

Route::group([
    'namespace'     => 'Backend',
    'prefix'        => 'backend',
    'middleware'    => [ 'web', 'auth:admin' ],
], function() {
    // name prefix
    $name_prefix = [ 'as' => 'admin' ];

    //
    Route::get('/',                     'DashboardController@index')->name('backend');
    Route::get('/dashboard',            'DashboardController@dashboard')->name('admin.dashboard');
    Route::get('/dashboard/verticals',  'DashboardController@verticals')->name('admin.dashboard.verticals');

    // users
    Route::resource('admins',   'AdminsController', $name_prefix)->name('index', 'admin.admins')->parameters([ 'admins' => 'samsung' ]);
    Route::resource('users',    'UsersController', $name_prefix)->name('index', 'admin.users');
    Route::get('solicitudes',    'UsersController@solicitudes')->name('admin.solicitudes');
    Route::post('solicitudes/{id}',    'UsersController@solicitud')->name('admin.solicitud');
    Route::get('rechazados',    'UsersController@rechazados')->name('admin.rechazados');
    
    //
    Route::resource('divisions',        'DivisionsController', $name_prefix)->name('index', 'admin.divisions');
    Route::resource('subcategorias',        'SubCategoriaController', $name_prefix)->name('index', 'admin.subcategorias');
    Route::resource('images',           'ImagesController', $name_prefix)->name('index', 'admin.images')->parameters([ 'files' => 'image' ]);
    Route::resource('products',         'ProductsController', $name_prefix)->name('index', 'admin.products');
    Route::post('stock/{id}', 'ProductsController@stock')->name('admin.stock');
    Route::resource('companies',        'CompaniesController', $name_prefix)->name('index', 'admin.companies');
    Route::resource('verticals',        'VerticalsController', $name_prefix)->name('index', 'admin.verticals');
    Route::resource('opportunities',    'OpportunitiesController', $name_prefix)->name('index', 'admin.opportunities');
    Route::resource('offers',           'OffersController', $name_prefix)->name('index', 'admin.offers');

    // private storage
    Route::get('storage/{file}',        'StorageController@get')->name('storage.get');
    //acciones que otorgan puntos
    Route::get('acciones', 'AccionController@index')->name('admin.acciones');
    Route::post('acciones/update/{id}', 'AccionController@update')->name('admin.acciones.update');

    Route::get('proteccion', 'ProtectController@oportunidades_pendientes')->name('admin.proteccion');
    Route::get('leads', 'OpportunitiesController@leads')->name('admin.leads');
    Route::get('leads/{id}', 'OpportunitiesController@lead')->name('admin.lead');
    Route::post('lead/{id}', 'OpportunitiesController@otorgar_lead')->name('admin.otorgar_lead');
    Route::get('oportunidad/{id}', 'ProtectController@oportunidad')->name('admin.proteccionShow');
    Route::post('proteccion/oportunidad', 'ProtectController@proteccion')->name('admin.proteccion_state');
    Route::get('opp_protegidas', 'ProtectController@opp_protegidas')->name('admin.opp_protegidas');
    Route::get('opp_rechazadas', 'ProtectController@opp_rechazadas')->name('admin.opp_rechazadas');

    //ranks
    Route::get('rank_puntos', 'RankingController@rank_puntos')->name('admin.rank_puntos');
    Route::get('rank_puntos/periodo', 'RankingController@rank_puntos_periodo')->name('admin.rank_puntos_periodo');

    Route::get('rank_oportunidades', 'RankingController@rank_opp')->name('admin.rank_oportunidades');
    Route::get('rank_oportunidades/periodo', 'RankingController@rank_oportunidades_periodo')->name('admin.rank_oportunidades_periodo');
    
    Route::get('rank_monto', 'RankingController@rank_monto')->name('admin.rank_monto');
    Route::get('rank_monto/periodo', 'RankingController@rank_monto_periodo')->name('admin.rank_monto_periodo');

    Route::post('oportunidad/precio/{id}', 'OpportunitiesController@precio_asignado')->name('admin.oportunidad_precio');
  
    Route::post('/addProductOpp',  'OpportunitiesController@addProductOpp');
    Route::post('/deleteOppProduct', 'OpportunitiesController@deleteOppProduct');
    Route::delete('/opportunities/{id}', 'OpportunitiesController@destroy')->name('opportunities.destroy');

});

bo/routes/frontend.php
<?php

/*
|--------------------------------------------------------------------------
| Public with authentication needed
|--------------------------------------------------------------------------
*/
Route::group([
    'namespace'     => 'Frontend',
], function() {
    Route::get('/register_client', 'UserController@create');
    Route::post('/register_client', 'UserController@store')->name('register_client');
});
Route::group([
    'namespace'     => 'Frontend',
    'middleware'    => [ 'auth' ],
], function() {
    // dashboard
    Route::get('/dashboard',            'DashboardController@index')->name('dashboard');

    Route::resource('opportunities',            'OpportunitiesController', [
        'only'  => [ 'show', 'create', 'edit', 'update', 'store' ],
        'names' => [ 'index' => 'opportunities.show' ]
    ]);
    Route::resource('opportunities.offers',     'OffersController', [
        'only'  => [ 'show', 'create', 'store', 'update', 'edit', 'destroy' ],
        'names' => [ 'index' => 'opportunities.offers' ]
    ]);
    Route::put('opportunities/{opportunity}/offers/{offer}/accept', 'OffersController@accept')->name('opportunities.offers.accept');
    Route::put('opportunities/{opportunity}/offers/{offer}/reject', 'OffersController@reject')->name('opportunities.offers.reject');
    Route::resource('products',                 'PricesController', [
        'only'  => [ 'index', 'update' ],
        'names' => [ 'index' => 'products' ]
    ]);

    //json
    Route::get('/listProducts',            'OpportunitiesController@listProducts');
    Route::get('/listOppProducts',            'OpportunitiesController@listOppProducts');
    Route::post('/addProductOpp',  'OpportunitiesController@addProductOpp');
    Route::post('/deleteOppProduct', 'OpportunitiesController@deleteOppProduct');

    // private storage
    Route::get('storage/{file}',        'StorageController@get')->name('frontstorage.get');
    Route::post('opportunities/precio_solicitado/{id}', 'OpportunitiesController@precio_solicitado');
    Route::post('opportunities/aprobado/{id}', 'OpportunitiesController@aprobado');
    Route::post('opportunities/cerrar/{id}', 'OpportunitiesController@cerrar');
    Route::post('opportunities/perder/{id}', 'OpportunitiesController@perder');
    Route::post('opportunities/estado', 'DashboardController@actualizar');
    Route::post('opportunities/mail', 'OpportunitiesController@mail');
    Route::post('opportunities/obtener/{id}', 'OpportunitiesController@obtener');
});

bo/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Public
|--------------------------------------------------------------------------
*/
Route::group([
    'namespace'     => 'Frontend'
], function() {
    //
 //   Route::get('/',         'SiteController@index');
    Route::get('/',         function(){
        return redirect('/login');
    });
    Route::get('/home',     'SiteController@index');
    // Route::get('/contact',  'SiteController@contact');
    // web login endpoints
    Auth::routes();
});

bo/app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\Company;
use App\Models\Opportunity;
use App\Models\Vertical;
use App\Models\User;
use Illuminate\Support\Facades\DB;

class DashboardController extends BackendController {
    public function __construct() {
        //
        parent::__construct();
        // force login
        $this->middleware('auth:admin');
    }

    public function index() {
        // redirect to dashboard
        return redirect()->route('admin.dashboard');
    }

    public function dashboard() {

        $fecha = date('Y-m');
        $ranks = $this->ranking_position($fecha);
        // load all opportunities
        $opportunities = Opportunity::all();
        // calculate counts
        $count = (object)[];
        foreach ($opportunities as $opportunity) {
            // init counter for state
            if (!isset($count->{$opportunity->state})) $count->{$opportunity->state} = 0;
            // increment counter
            $count->{$opportunity->state}++;
        }
        $opportunities = $opportunities->sortByDesc('created_at');
        //dd($count, $opportunities);
        // load companies count
        $companies = Company::groupBy('type')->select('type', DB::raw('count(*) as total'))->get();
        // show dashboard view
        return view('dashboard.index', compact('opportunities', 'count', 'companies','ranks'));
    }

    public function ranking_position($fecha){
        $companies = Company::where('type', 'reseller')->get();
        $users = User::all();
        foreach ($companies as $key_comp => $comp) {
            $companies[$key_comp]->puntos = $companies[$key_comp]->puntos + 0;
            foreach ($comp->users as $key_user => $user) {
                foreach ($user->puntajes as $key_punt => $puntaje) {
                    $fecha_punt = substr($puntaje->created_at, 0, 7);
                    if ($fecha == $fecha_punt ) {
                        $companies[$key_comp]->puntos = $companies[$key_comp]->puntos + $puntaje->puntos;
                    }
                }
            }
        }

        $companies = $companies->sortByDesc('puntos');
        $position = 0;
        foreach ($companies as $key => $comp) {
            $position = $position + 1;
            $companies[$key]->position = $position;
        }
        return $companies;
    }

    public function verticals() {
        // load verticales
        $verticals = Vertical::with('companies.users.opportunities')->get();
        dd($verticals);
        // foreach verticals
        foreach ($verticals as $vertical) {
            // counters [ empresas , pantallas ]
            $vertical->totals = (object)[
                'totals'    => [ 0, 0 ],
                'bo'        => [ 0, 0 ],
                'leads'     => [ 0, 0 ],
                'available' => [ 0, 0 ],
            ];
            // foreach companies
            foreach ($vertical->companies as $company) {
                // add empresas counter
                $vertical->totals->totals[0]++;
                $vertical->totals->totals[1] += $company->branches * $company->avg_branches;
                // foreach opportunities
                foreach ($company->opportunities as $opportunity) {
                    // check OP status
                    if ($opportunity->state == 'lead') {
                        // add product qty
                        $vertical->totals->leads[0]++;
                    } elseif ($opportunity->state == 'open') {
                        // add product qty
                        $vertical->totals->bo[0]++;
                    }
                    // foreach opportunity products
                    foreach ($opportunity->products as $product) {
                        // check OP status
                        if ($opportunity->state == 'lead') {
                            // add product qty
                            $vertical->totals->leads[1] += $product->pivot->quantity;
                        } elseif ($opportunity->state == 'open') {
                            // add product qty
                            $vertical->totals->bo[1] += $product->pivot->quantity;
                        }
                    }
                }
            }
            // calculate available
            $vertical->totals->available[0] = $vertical->totals->totals[0] - $vertical->totals->bo[0] - $vertical->totals->leads[0];
            $vertical->totals->available[1] = $vertical->totals->totals[1] - $vertical->totals->bo[1] - $vertical->totals->leads[1];
        }
        // show dashboard view
        return view('dashboard/verticals', compact('verticals'));
    }
}

bo/app/Http/Controllers/Frontend/FrontendController.php
<?php

namespace App\Http\Controllers\Frontend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

abstract class FrontendController extends Controller {
    public function __construct() {
        // add base path for frontend views
        view()->addLocation(resource_path('views/frontend/'));
    }
}

bo/app/Http/Controllers/Frontend/PricesController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Frontend\FrontendController;
use App\Models\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class PricesController extends FrontendController {
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        // fetch
        $products = Product::fromMayorista(Auth::user()->company_id)->get();
        // show create form
        return view('prices.index', compact('products'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Offer  $offer
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request) {
        // foreach products to update price
       // dd($request);
        $products = [];
        foreach ($request->products as $idx => $product_id) {
            // get Product to update
            $product = Product::findOrFail($product_id);
            // fill params
            $product->fill([
                'price' => $request->price[$idx]
            ]);
            // save resource
         //   dd($product);
            if (!$product->save())
                // redirect with errors
                return redirect()
                    ->back()
                    ->withErrors($product->errors());
        }
        // redirect to list
        return redirect()->route('products');
    }
}

bo/app/Http/Controllers/Frontend/SiteController.php
<?php

namespace App\Http\Controllers\Frontend;

class SiteController extends FrontendController {
    public function index() {
        return view('site/index');
    }

    // public function contact() {
    //     return view('site/contact');
    // }
}

bo/app/Http/Controllers/Frontend/StorageController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Models\File;
use Illuminate\Filesystem\Filesystem;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Storage;

class StorageController extends FrontendController {
    public function get(File $file) {
        // get file
        $storage = Storage::get($file->url);
        // create a response with file data
        $response = new Response($storage, 200);
        // append file mime type as content type
        $response->header('Content-Type', Storage::mimeType($file->url));
        // return response data
        return $response;
    }
}

bo/resources/views/frontend/dashboard/index.blade.php
@extends('layouts.master')

@section('content')

{{-- load user dashboard by type --}}
@include('dashboard.'.Auth::user()->type)

@endsection

bo/resources/views/frontend/dashboard/mayorista.blade.php
@extends('layouts.master')

@section('content')


<div class="row justify-content-center mb-4">
    <div class="col-12 col-md-12 mb-4">
        <a>
            <img class="img-responsive" src="{{ url('/assets/img/header.jpg') }}" style="width:100%; " alt=""/>
        </a>
    </div>
    <div class="col">
        <div class="card">
            <div class="card-header bg-primary text-white py-3">
                <div class="row">
                    <div class="col d-flex align-items-center">
                        <h6 class="m-0 font-weight-bold">{{ __('Leads disponibles') }}</h6>
                    </div>
                    <div class="col mr-auto d-flex justify-content-end">
                        {{-- <a href="{{ route('opportunities.create') }}" class="btn btn-sm btn-primary">Crear nueva Oportunidad</a> --}}
                    </div>
                </div>
            </div>

            <div class="card-body bg-light">

                @php
                // solo leads sin mayorista
                $leads = $leads->filter(function($lead) {
                    return $lead->mayorista_id === null;
                });
                @endphp
                @if (count($leads) > 0)

                    <div class="row">
                        <div class="col-2">
                            <h5 class="font-weight-bold">Nombre</h5>
                        </div>
                        <div class="col-2">
                            <h5 class="font-weight-bold">Compañía</h5>
                        </div>
                        <div class="col-2">
                            <h5 class="font-weight-bold">Reseller</h5>
                        </div>
                        <div class="col-2">
                            <h5 class="font-weight-bold">Puntos</h5>
                        </div>
                        <div class="col-2">
                            <h5 class="font-weight-bold">Monto</h5>
                        </div>
                    </div>
                    {{-- Reseller opportunities --}}
                    @foreach($leads as $opportunity)
                        @include('dashboard.mayorista.lead')
                    @endforeach

                @else

                    <div class="text-center m-t-30 m-b-30 p-b-10">
                        <em>No hay Leads disponibles</em>
                    </div>

                @endif
            </div>

        </div>
    </div>
</div>


<div class="row justify-content-center mb-4">
    <div class="col">
        <div class="card border-left-primary">
            <div class="card-header py-3">
                <div class="row">
                    <div class="col d-flex align-items-center">

                        <ul class="nav nav-pills" id="pills-tab" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link btn-icon-split p-3 mr-2 font-weight-bold active" id="pills-open-tab"
                                    data-toggle="pill" href="#pills-open" role="tab" aria-controls="pills-open"
                                    aria-selected="true">
                                    <span class="icon d-flex align-items-center">
                                        <i class="fas fa-clipboard-list"></i>
                                    </span>
                                    <span class="text">{{ __('Oportunidades en curso') }}</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link btn-icon-split p-3 mr-2 font-weight-bold" id="pills-won-tab"
                                    data-toggle="pill" href="#pills-won" role="tab" aria-controls="pills-won"
                                    aria-selected="false">
                                    <span class="icon d-flex align-items-center">
                                        <i class="fas fa-dollar-sign"></i>
                                    </span>
                                    <span class="text">{{ __('Oportunidades ganadas') }}</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link btn-icon-split p-3 mr-2 font-weight-bold" id="pills-lost-tab"
                                    data-toggle="pill" href="#pills-lost" role="tab" aria-controls="pills-lost"]
                                    aria-selected="false">
                                    <span class="icon d-flex align-items-center">
                                        <i class="fas fa-thumbs-down"></i>
                                    </span>
                                    <span class="text">{{ __('Oportunidades perdidas') }}</span>
                                </a>
                            </li>
                        </ul>

                        {{-- <h6 class="m-0 font-weight-bold text-info">{{ __('Oportunidades en curso') }}</h6> --}}
                    </div>
                    <div class="col mr-auto d-flex justify-content-end">
                        <a href="{{ route('opportunities.create') }}" class="btn btn-lg btn-primary btn-icon-split font-weight-bold p-3">
                            <span class="icon d-flex align-items-center">
                                <i class="fas fa-plus"></i>
                            </span>
                            <span class="text">Crear nueva Oportunidad</span>
                        </a>
                        {{-- <a href="{{ route('opportunities.create') }}" class="btn btn-lg btn-primary font-weight-bold p-3">Crear nueva Oportunidad</a> --}}
                    </div>
                </div>
            </div>

            <div class="card-body bg-light">

                <div class="tab-content" id="pills-tabContent">
                    <div class="tab-pane fade show active" id="pills-open" role="tabpanel" aria-labelledby="pills-open-tab">

                        @php
                        $open = $opportunities->filter(function($opportunity) {
                            return
                                // state open
                                in_array($opportunity->state, [ 'open' ]) ||
                                // lead & mayorista=this
                                $opportunity->state == 'lead' && $opportunity->mayorista_id == Auth::user()->company_id;
                        });
                        @endphp
                        @if (count($open) > 0)

                            <div class="row">
                                <div class="col-2">
                                    <h5 class="font-weight-bold">Nombre</h5>
                                </div>
                                <div class="col-2">
                                    <h5 class="font-weight-bold">Reseller</h5>
                                </div>
                                <div class="col-2 text-center">
                                    <h5 class="font-weight-bold">Puntos</h5>
                                </div>
                                <div class="col-2 text-center">
                                    <h5 class="font-weight-bold">Monto</h5>
                                </div>
                                <div class="col-2 text-center">
                                    <h5 class="font-weight-bold">Estado</h5>
                                </div>
                            </div>

                            {{-- Open opportunities --}}
                            @foreach($open as $opportunity)
                                @include('dashboard.mayorista.open')
                            @endforeach

                        @else

                            <div class="text-center m-t-30 m-b-30 p-b-10">
                                <em>No tienes oportunidades en curso</em>
                            </div>

                        @endif

                    </div>
                    <div class="tab-pane fade" id="pills-won" role="tabpanel" aria-labelledby="pills-won-tab">

                        @php
                        $won = $opportunities->filter(function($opportunity) {
                            return $opportunity->state == 'won';
                        });
                        @endphp
                        @if (count($won) > 0)

                            <div class="row">
                                <div class="col-6">
                                    <h5 class="font-weight-bold">Nombre</h5>
                                </div>
                                <div class="col-4">
                                    <h5 class="font-weight-bold">Compañía</h5>
                                </div>
                            </div>

                            {{-- Open opportunities --}}
                            @foreach($won as $opportunity)
                                @include('dashboard.mayorista.won')
                            @endforeach

                        @else

                            <div class="text-center m-t-30 m-b-30 p-b-10">
                                <em>No tienes oportunidades ganadas</em>
                            </div>

                        @endif

                    </div>
                    <div class="tab-pane fade" id="pills-lost" role="tabpanel" aria-labelledby="pills-lost-tab">

                        @php
                        $lost = $opportunities->filter(function($opportunity) {
                            return in_array($opportunity->state, [ 'lost' ]);
                        });
                        @endphp
                        @if (count($lost) > 0)

                            <div class="row">
                                <div class="col-6">
                                    <h5 class="font-weight-bold">Nombre</h5>
                                </div>
                                <div class="col-4">
                                    <h5 class="font-weight-bold">Compañía</h5>
                                </div>
                            </div>

                            {{-- Open opportunities --}}
                            @foreach($lost as $opportunity)
                                @include('dashboard.mayorista/lost')
                            @endforeach

                        @else

                            <div class="text-center m-t-30 m-b-30 p-b-10">
                                <em>No tienes oportunidades perdidas</em>
                            </div>

                        @endif

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection